### ISSUE TITLE
support  deploy custom modules

### ISSUE THREAD

**Issue by nanne007** [starcoinorg/test-dapp#7]
So that user can upload multi mv files, and specify an init script function call.

**Comment by jolestar** [comment]
如果上传 mv 文件构造 Package 实现比较复杂，可以先支持上传 Package 文件或者 Package hex，用户通过 starcoin cli 来打包 package。

**Comment by wk3368** [comment]
![image](https://user-images.githubusercontent.com/171268/126470412-36c65afb-f7fb-4d57-a2c5-d72b6def5b78.png)
customer can use starcoin cli to  generate the package hex，then paste the hex and deploy here.
