### ISSUE TITLE
support encrypt/decrypt

### ISSUE THREAD

**Issue by wk3368** [starcoinorg/test-dapp#8]
![image](https://user-images.githubusercontent.com/171268/130328338-ad26316a-951c-40e4-bedd-e7bdbca8b665.png)

need support in js sdk first

**Comment by bulangnisi** [comment]
Hope to add quickly, business needs 👍👍👍

**Comment by wk3368** [comment]
<img width="1866" alt="WX20210926-120821@2x" src="https://user-images.githubusercontent.com/171268/134793573-3fe365b3-3cca-4afd-ae86-1a8e58a4dc8a.png">

<img width="1866" alt="WX20210926-120619@2x" src="https://user-images.githubusercontent.com/171268/134793578-7e6c0797-5eec-4708-bf10-f47c1b346b39.png">

starmask-test-dapp@1.4.0

starmask-extension@2.2.1
