### ISSUE TITLE
Support custom the contract function and setting arguments for call and execute function

### ISSUE THREAD

**Issue by jolestar** [starcoinorg/test-dapp#9]
A user wants to call or execute a function in the module:

Support user input a module name and function name and setting arguments the execute it with a transaction or call it for query state.

Relative API:

1. `contract.resolve_function`: Get a function ABI.
2. `contract.call_v2`: Call a read-only function for query state.

**Comment by jolestar** [comment]
#10 only implement query state by `contract.call_v2`, do not implement execute a script function by a transaction. reopen this.

**Comment by yubing744** [comment]
This code  implements execute a script function by a transaction in https://github.com/starcoinorg/starmask-test-dapp/pull/10.

![image](https://user-images.githubusercontent.com/1449069/159385812-0e774bc0-ba7e-48c6-9c92-370cc38819e3.png)

**Comment by yubing744** [comment]
> #10 only implement query state by `contract.call_v2`, do not implement execute a script function by a transaction. reopen this.

This code implement execute a script function by a transaction in #10 .

![image](https://user-images.githubusercontent.com/1449069/159388097-7de03842-9e94-4391-92d8-f08a220a2e65.png)
